#! /bin/bash
# Donate: http://bit.ly/CBLDonate Every donation keeps the future development going. Thank you.
# Contribute: https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/new
# Copyright: (c) ZeroDot1, 2019
# Description: This is a simple tool called Listscleaner to clean the CoinBlockerLists from garbage.
# Homepage: https://gitlab.com/ZeroDot1/CoinBlockerLists/
# Last modified: 2019-04-28 22:40
# License: https://gitlab.io/ZeroDot1/CoinBlockerLists/LICENSE
# [CoinBlocker Listscleaner by ZeroDot1]
cd /home/user/Dokumente/GitLab/CoinBlockerLists/
mv list.txt list.tmp
mv list_browser.txt list_browser.tmp
comm  -23 <(sort list.tmp) <(sort white_list.txt) >> tmpc.txt
sleep 1s
comm  -23 <(sort list_browser.tmp) <(sort white_list.txt) >> tmpd.txt
sleep 1s
# Buglist Generated by PyFunceble Thanks to: https://github.com/funilrys
comm  -23 <(sort tmpc.txt) <(sort bugs.txt) >> tmpc1.txt
sleep 1s
sort tmpc1.txt | uniq >> list.txt
sort tmpd.txt | uniq >> list_browser.txt
# mv tmpd.txt list_browser.txt
rm -rf list_browser.tmp list.tmp tmpc.txt tmpd.txt tmpc1.txt
